PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0
MATRIXX_BUILD_TYPE ?= UNOFFICIAL

# Increase MATRIXX Version with each major release.
MATRIXX_VERSION := 6.0

# Internal version
LINEAGE_VERSION := Matrixx-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(MATRIXX_VERSION)-$(MATRIXX_BUILD_TYPE)

# Display version
LINEAGE_DISPLAY_VERSION := Matrixx-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(MATRIXX_VERSION)-$(MATRIXX_BUILD_TYPE)

ifeq ($(MATRIXX_BUILD_TYPE), OFFICIAL)
  OFFICIAL_DEVICES = $(shell cat vendor/lineage/matrixx.devices)
  FOUND_DEVICE =  $(filter $(LINEAGE_BUILD), $(OFFICIAL_DEVICES))
    ifeq ($(FOUND_DEVICE),$(LINEAGE_BUILD))
      MATRIXX_BUILD_TYPE := OFFICIAL
    else
      MATRIXX_BUILD_TYPE := UNOFFICIAL
    endif
endif    
